### ISSUE TITLE
Error: No code sections found

### ISSUE THREAD

**Issue by chipit24** [NekR/offline-plugin#314]
When using with [webpack-dashboard](https://github.com/FormidableLabs/webpack-dashboard), I get the following error:
```
...
webpack: Compiled successfully.
Worker error Error: No code sections found
    at Bundle.validate (/Users/.../test_with_offline_plugin/node_modules/inspectpack/lib/models/bundle.js:54:11)
    at createBundle (/Users/.../test_with_offline_plugin/node_modules/inspectpack/lib/models/bundle.js:262:12)
    at Immediate.setImmediate [as _onImmediate] (/Users/.../test_with_offline_plugin/node_modules/inspectpack/lib/models/bundle.js:313:7)
    at runCallback (timers.js:781:20)
    at tryOnImmediate (timers.js:743:5)
    at processImmediate [as _immediateCallback] (timers.js:714:5)
...
```

A minimum repo with the issue: https://github.com/chipit24/test_with_offline_plugin
Just pull down and `yarn && yarn start` to see the problem.

If you run the actual dashboard (see `start-dashboard` script in linked repo), you'll get a different error:
```
$ yarn start-dashboard
yarn run v1.2.1
$ webpack-dashboard -- webpack-dev-server
TypeError: Cannot read property 'meta' of undefined
    at assets.filter.map.asset (/Users/.../test_with_offline_plugin/node_modules/webpack-dashboard/utils/format-assets.js:28:40)
    at Array.map (<anonymous>)
    at _.flatMap.assets (/Users/.../test_with_offline_plugin/node_modules/webpack-dashboard/utils/format-assets.js:24:8)
    at l (/Users/.../test_with_offline_plugin/node_modules/lodash/lodash.min.js:6:443)
    at uu (/Users/.../test_with_offline_plugin/node_modules/lodash/lodash.min.js:67:252)
    at On.flatMap (/Users/.../test_with_offline_plugin/node_modules/lodash/lodash.min.js:99:101)
    at l (/Users/.../test_with_offline_plugin/node_modules/lodash/lodash.min.js:50:137)
    at resolveAssets (/Users/.../test_with_offline_plugin/node_modules/webpack-dashboard/utils/format-assets.js:32:4)
    at printAssets (/Users/.../test_with_offline_plugin/node_modules/webpack-dashboard/utils/format-assets.js:36:18)
    at formatAssets (/Users/.../test_with_offline_plugin/node_modules/webpack-dashboard/utils/format-assets.js:55:10)
error Command failed with exit code 1.
info Visit https://yarnpkg.com/en/docs/cli/run for documentation about this command.
```

**Comment by NekR** [comment]
@chipit24 Hi! Sorry, I somehow missed this issue. I'll take a look at the provided, repo thanks!

**Comment by NekR** [comment]
https://github.com/chipit24/test_with_offline_plugin/blob/master/webpack.config.js#L24-L25

@chipit24 `offline-plugin` should be the last plugin added to the array. Having it the last solved the problem?

**Comment by chipit24** [comment]
Thanks for looking into this @NekR. I tried placing `offline-plugin` last but still got errors. When I run this with webpack-dashboard (`webpack-dashboard -- webpack-dev-server`) I still got an error  and the dashboard would exit with `TypeError: Cannot read property 'meta' of undefined`. Same errors I posted above.

Maybe I can post this issue in the webpack-dashboard repo as well.

**Comment by NekR** [comment]
@chipit24 
> Maybe I can post this issue in the webpack-dashboard repo as well.

That may make sense. I have no idea what they're doing in their plugin, but looks like they looking for JS chunks to be attached to the compilation at some point and they aren't. IMO, if any, that should be a warning, not a fatal error.

**Comment by iroy2000** [comment]
I'm having the same issues, I wonder if anyone knows how to resolve this.

**Comment by NekR** [comment]
No clue.
