### ISSUE TITLE
Problem with Webpack 5.0

### ISSUE THREAD

**Issue by sergeushenecz** [NekR/offline-plugin#491]
Hello everyone. I have some problem when  i updating from webpack 4 to 5 version. When i build project  i have error in the console. 

![image](https://user-images.githubusercontent.com/7217517/95685659-e2880e00-0c01-11eb-9dd9-e558b5d02fa1.png)

Error in line code.
![image](https://user-images.githubusercontent.com/7217517/95687394-123c1380-0c0c-11eb-9185-12fc11dc3070.png)

**Comment by Enase** [comment]
the same issue for me.
Some more details:
`result.resource` is `undefined`. 
It can be accessed at `result.createData.resource` but then the following:

```
Uncaught exception: Error: NormalModuleFactory.afterResolve is no longer a waterfall hook, but a bailing hook instead. Do not return the passed object, but modify it instead. Returning false will ignore the request and results in no module created.
```

**Comment by sergeushenecz** [comment]
@Enase  I found an issue https://github.com/webpack/webpack/issues/11647 The same problem. I think plugin not supported the new version webpack.

**Comment by Enase** [comment]
@sergeu90 ic, it's true. thanks.

**Comment by sergeushenecz** [comment]
@NekR Hello. Are we planning to upgrade to webpack 5?

**Comment by sergeushenecz** [comment]
Can anyone have experience writing a plugin for webpack? Maybe anyone fork and rewrite this library

**Comment by Enase** [comment]
The last release was done about two years ago. I don't believe that we find any help here.

**Comment by sergeushenecz** [comment]
Does it mean the plugin is dead? Maybe Are there alternative plugins?

**Comment by gowrav-scienaptic** [comment]
https://developers.google.com/web/tools/workbox/modules/workbox-webpack-plugin

**Comment by sergeushenecz** [comment]
@gowrav-scienaptic  Can you explain? Is it alternative plugin?

**Comment by gowrav-scienaptic** [comment]
@sergeu90, Yes it's an alternative for offline-plugin. You can read the details on how to integrate [here](https://webpack.js.org/guides/progressive-web-application/).

**Comment by timminata** [comment]
We are using offline-plugin and attempting to upgrade to Webpack 5. Should we wait for this issue to be resolved or is this no longer maintained?

**Comment by Enase** [comment]
@timminata plugin author doesn't reply over two years. Unfortunately, the answer is yes.

**Comment by sergeushenecz** [comment]
@gowrav-scienaptic  Thanks. I migrated to workbox.

**Comment by LeComptoirDesPharmacies** [comment]
Hello guys ! 
Our team needs offline-plugin to work with Webpack 5, so we worked on a fix here : https://github.com/NekR/offline-plugin/pull/498

Enjoy :)
LCDP,

**Comment by LeComptoirDesPharmacies** [comment]
Hello again guys ! 
Our team forked and worked on a relase candidate that work with Webpack 5, it's available here => https://www.npmjs.com/package/@lcdp/offline-plugin

Any feedback are welcome, we need you to improve the compatibility with webpack 5 !

**Comment by Enase** [comment]
@LeComptoirDesPharmacies Unfortunately it's not possible to create issue in your github repo.
There is an issue while webpack build with your implementation:
```
(node:18736) [DEP_WEBPACK_COMPILATION_CACHE] DeprecationWarning: Compilation.cache was removed in favor of Compilation.getCache()
    at compilationFn (......./node_modules/@lcdp/offline-plugin/lib/service-worker.js:142:25)
    at _next36 (eval at create (......../node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:50:1)
    at _next14 (eval at create (......../node_modules/tapable/lib/HookCodeFactory.js:19:10), <anonymous>:97:1)
```
and
```
BREAKING CHANGE: No more changes should happen to Compilation.assets after sealing the Compilation.
	Do changes to assets earlier, e. g. in Compilation.hooks.processAssets.
	Make sure to select an appropriate stage from Compilation.PROCESS_ASSETS_STAGE_*.
    at ServiceWorker.apply (....../node_modules/@lcdp/offline-plugin/lib/service-worker.js:192:35)
```

**Comment by LeComptoirDesPharmacies** [comment]
@Enase Sorry for this, we have enabled the issues on our repo.

Thank you for your feedback, as we use webpack 5 in production we should fix this depreciation warning before it becomes really breaking. 

Do it break your build ?

We have the same warning, but everything works like a charm.

If you see others warnings, don't hesitate to open an issue on our repo, know it's working 💯 

Yours faithfully,
LCDP
